# Generated by Django 3.2.5 on 2021-07-20 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0003_auto_20210711_0228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id'], 'verbose_name': 'товар', 'verbose_name_plural': 'товары'},
        ),
        migrations.AlterModelOptions(
            name='stockproduct',
            options={'verbose_name': 'Товар на склад', 'verbose_name_plural': 'Товар на складе'},
        ),
    ]
